# Generated by Django 4.2.16 on 2024-09-24 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chalet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Chalet's name")),
                ('image', models.ImageField(blank=True, null=True, upload_to='chalets/', verbose_name="Chalet's picture")),
                ('country', models.CharField(choices=[('FR', 'France'), ('CH', 'Switzerland')], default='FR', max_length=2, verbose_name='Country')),
                ('review', models.TextField(blank=True, verbose_name='My opinion')),
                ('chalet_link', models.URLField(verbose_name="Chalet's link")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Chalet's price")),
                ('ski_resort_link', models.URLField(verbose_name='Ski link')),
                ('approximate_travel_time', models.CharField(max_length=100, verbose_name='Approximate time from the airport')),
                ('beds', models.PositiveIntegerField(verbose_name='The amount of beds in the Chalet')),
            ],
        ),
        migrations.CreateModel(
            name='UserReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('chalet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chalets.chalet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'chalet')},
            },
        ),
    ]
